### ISSUE TITLE
[Need Help] Could I directly call libcronet.so from cronet-go?

### ISSUE THREAD

**Issue by diyism** [sleeyax/cronet-binaries#1]
I'm trying to directly call libcronet.so(extracted from https://github.com/sleeyax/cronet-binaries/releases/download/v119.0.6045.66/cronet-v119.0.6045.66-linux-x64.tar.xz) from cronet-go(https://github.com/SagerNet/cronet-go),
I've extracted cronet-v119.0.6045.66-linux-x64.tar.xz into /home/malcolm/cronet-v119.0.6045.66-linux-x64

and my cgo flags:
`#cgo LDFLAGS: -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program -m64 -no-canonical-prefixes -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O2 -pie -Wl,--disable-new-dtags -ldl -lpthread -lrt /home/malcolm/cronet-v119.0.6045.66-linux-x64/libcronet.so -Wl,-rpath,/home/malcolm/cronet-v119.0.6045.66-linux-x64`

my test.go:
```
package main

import (
	"net/http"
	"os"
	"github.com/sagernet/cronet-go"
)


func main() {
	client := &http.Client{
		Transport: &cronet.RoundTripper{},
	}
	response, err := client.Get("https://www.google.com/ncr")
	if err != nil {
	}
	response.Write(os.Stderr)
	response.Body.Close()
}
```

but when I run "CGO_LDFLAGS_ALLOW=".*" go run test.go", it says:
```
runtime: pcHeader: magic= 0xfffffff1 pad1= 0 pad2= 0 minLC= 1 ptrSize= 8 pcHeader.textStart= 0x266180 text= 0x5644834fc180 pluginpath= 
fatal error: invalid function symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw({0x56448332b4da?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1658 +0x5c fp=0x7ffd2147f688 sp=0x7ffd2147f658 pc=0x56448353147c
runtime.moduledataverify1(0x8?)
	/usr/local/go/src/runtime/symtab.go:806 +0x816 fp=0x7ffd2147f7a8 sp=0x7ffd2147f688 pc=0x56448354ea16
runtime.moduledataverify(...)
	/usr/local/go/src/runtime/symtab.go:784
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:1085 +0x34 fp=0x7ffd2147f7f0 sp=0x7ffd2147f7a8 pc=0x564483534f94
runtime.rt0_go()
	/usr/local/go/src/runtime/asm_amd64.s:349 +0x11c fp=0x7ffd2147f7f8 sp=0x7ffd2147f7f0 pc=0x5644835605fc
exit status 2
```

Could I directly call libcronet.so from cronet-go?

**Comment by sleeyax** [comment]
Thank you for reporting this issue, I'm glad someone else besides me is trying out the binaries as they are still relatively experimental! 

I believe you're missing the `CC=clang` environment variable to specify the C compiler to use when building your code:
` LD_LIBRARY_PATH=/home/malcolm/cronet-v119.0.6045.66-linux-x64/  CGO_LDFLAGS_ALLOW=".*"  CC=clang  go run test.go`

--- 

Please keep an eye on my fork https://github.com/sleeyax/cronet-go/tree/develop of https://github.com/sagernet/cronet-go (pretty much no longer maintained at the time of writing), it goes hand in hand with this repo and I would love some contributors helping to improving the DX of compiling cronet with go, if you have time to spare.

**Comment by diyism** [comment]
Cool, it works, you saved my day. Thanks.

I've modified the https://github.com/SagerNet/cronet-go/blob/main/link_shared_linux_amd64.go into:
```
//go:build !cronet_static

package cronet

// #cgo LDFLAGS: -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy=cache_size=10%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -m64 -no-canonical-prefixes -rdynamic -Wl,-z,defs -Wl,--as-needed -Wl,--lto-O2 -pie -Wl,--disable-new-dtags -ldl -lpthread -lrt /usr/lib/libcronet.so -Wl,-rpath,$ORIGIN
import "C"
```
Then:
`sudo install /home/malcolm/cronet-v119.0.6045.66-linux-x64/libcronet.so /usr/lib/`

And then I can run successfully:
```
go clean --cache
CGO_LDFLAGS_ALLOW=".*"  CC=clang  go run test.go
```

But I'm not so familiar with clang, so I'm afraid to make a pull request to the cronet-go project.

**Comment by sleeyax** [comment]
> I've modified the ...

Hmm although your changes work fine on your system (Ubuntu I presume), it won't work on other systems as `/usr/lib/libcronet.so` isn't a path that exists on every OS (e.g. Windows). That's why `cronet-go` targets a local `build` folder for linking instead. So I can't accept a pull request for those changes.

Anyways, I'm closing this issue now as a solution has been provided. Let me know if you bump into any other problems by creating a new issue.
