### ISSUE TITLE
How to use the shared library of  Android version ?

### ISSUE THREAD

**Issue by pendy99** [sleeyax/cronet-binaries#2]
As shown below, there seems to be no cronet symbol table in the android version of the shared library. How to call it?

```
U abort
         U __aeabi_memclr
         U __aeabi_memclr4
         U __aeabi_memclr8
         U __aeabi_memmove
         U __aeabi_memmove4
         U __aeabi_memset
         U android_set_abort_message
         U closelog
         U __ctype_get_mb_cur_max
         U __cxa_atexit
         U __cxa_finalize
         U __errno
         U fflush
         U fputc
         U fputwc
         U fwrite
         U getc
         U gettid
         U getwc
         U isdigit_l
         U islower_l
         U isupper_l
         U iswlower_l
         U isxdigit_l
         U madvise
         U mbrlen
         U memchr
         U memcmp
         U memcpy
         U memset
         U mmap
         U mprotect
         U munmap
         U __open_2
         U openlog
         U prctl
         U pthread_cond_broadcast
         U pthread_cond_wait
         U pthread_getspecific
         U pthread_key_create
         U pthread_key_delete
         U pthread_mutex_lock
         U pthread_mutex_unlock
         U pthread_once
         U pthread_setspecific
         U __read_chk
         U __register_atfork
         U snprintf
         U sscanf
         U __stack_chk_fail
         U __stack_chk_guard
         U stderr
         U stdin
         U stdout
         U strcmp
         U strftime_l
         U strlen
         U strstr
         U strtod
         U strtof
         U strtoll
         U strtoull
         U syscall
         U syslog
         U ungetc
         U ungetwc
         U vfprintf
         U vsnprintf
         U __vsnprintf_chk
         U vsscanf
         U wcslen
         U wmemchr

```

**Comment by sleeyax** [comment]
Where did you get this binary? AFAIK cronet is more and more built into Android / Google services which could explain why the entry point is missing from whatever binary you have there. 

~~This project is meant for and thus only supports cronet for desktop.~~ EDIT: my mistake, I just woke up when I saw your issue in my mailbox and thought you created it on another repo of mine (which links back to this repo).

**Comment by pendy99** [comment]
https://github.com/sleeyax/cronet-binaries/releases/download/v119.0.6045.66/cronet-v119.0.6045.66-android-arm.tar.xz

**Comment by sleeyax** [comment]
To use cronet for Android you're better off following the [official guide](https://developer.android.com/develop/connectivity/cronet/start#set-up) instead. This repository just provides the binaries as is, with no further instructions on how to use them in your project. And I don't plan to include such instructions as they are very different per platform.
